### ISSUE TITLE
Regression: Fonts in snap apps become ugly and unexpected

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [ubuntu/snapcraft-desktop-helpers#117]
Before:
![screenshot_20180514_232704](https://user-images.githubusercontent.com/13408130/40107941-37ec9252-592c-11e8-9952-178ec88e1892.png)

Current:
![screenshot_20180516_171126](https://user-images.githubusercontent.com/13408130/40107929-30e464c6-592c-11e8-8105-8f1fada36a51.png)

I wonder if it is a regression of the recent fontconfig changes

**Comment by gerboland** [comment]
Likely yes, have you patch included?
https://github.com/ubuntu/snapcraft-desktop-helpers/pull/116

**Comment by Lin-Buo-Ren** [comment]
I don't have any patches available at the moment.

**Comment by gerboland** [comment]
Please try again rebuilding against the latest desktop-helpers (make sure to clean it first)

**Comment by oSoMoN** [comment]
That looks exactly like [bug #1771385](https://launchpad.net/bugs/1771385), I bet rebuilding that snap against the latest revision of the desktop helpers would make the issue go away.

**Comment by Lin-Buo-Ren** [comment]
I have rebuilt the package and the problem still persist :-/

Here's the build log https://build.snapcraft.io/user/Lin-Buo-Ren/poedit/220939
and the package if you are courageous: `snap install --edge poedit-wip-pr-468 --revision=20`

The source: https://github.com/vslavik/poedit/pull/468 / https://github.com/Lin-Buo-Ren/poedit/tree/wip-snappy-packaging

**Comment by oSoMoN** [comment]
I just installed the snap from the edge channel in a clean bionic VM, and fonts are rendered correctly:

![poedit](https://user-images.githubusercontent.com/11027549/40128827-f8d727e2-5932-11e8-804a-158b9bbf5c9d.png)

Did you follow Gerry's advice to uninstall and then reinstall the snap? This should remove everything under $HOME/snap/poedit-wip-pr-468/current, including the fontconfig configuration file generated by the desktop helpers.

**Comment by Lin-Buo-Ren** [comment]
I've removed the entire $HOME/snap and the package and reinstall it from the snap store.

![screenshot_20180517_010005](https://user-images.githubusercontent.com/13408130/40131859-b002e4c6-596d-11e8-9d6a-c74c5304e8df.png)

**Comment by Lin-Buo-Ren** [comment]
I can't reproduce it in my VM as well.  When I tried to run it under `snapcraft run --shell poedit-wip-pr-468` I noticed that:

* Running `poedit` after setting `PATH`, `LD_LIBRARY_PATH`, and LD_LIBRARY_PATH` manually without running `$SNAP/command-poedit.wrapper`, the issue is NOT reproduced
* Running `poedit` with `$SNAP/command-poedit-wrapper` the issue IS reproduced

Also `fc-match sans` returns different result with and without prepending with `$SNAP/bin/desktop-launch`

```
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ fc-match sans
NotoSansCJK-Regular.ttc: "Noto Sans CJK TC" "Regular"
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ ./bin/desktop-launch fc-match sans
TW-Kai-98_1.ttf: "全字庫正楷體" "Regular"
```

**Comment by Lin-Buo-Ren** [comment]
The matching results after resetting the locales:

```
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ LANG=C
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ locale
LANG=C
LANGUAGE=zh_TW:zh_CN
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_PAPER="C"
LC_NAME="C"
LC_ADDRESS="C"
LC_TELEPHONE="C"
LC_MEASUREMENT="C"
LC_IDENTIFICATION="C"
LC_ALL=
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ unset LANGUAGE
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ fc-match sans
NotoSans-Regular.ttf: "Noto Sans" "Regular"
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ fc-match serif
NotoSerif-Regular.ttf: "Noto Serif" "Regular"
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ ./bin/desktop-launch fc-match sans
FreeMono.ttf: "FreeMono" "Regular"
Lin-Buo-Ren@Lin-Buo-Ren-SSD480:/snap/poedit-wip-pr-468/20$ ./bin/desktop-launch fc-match serif
NotoSerif-Regular.ttf: "Noto Serif" "Regular"
```

**Comment by Lin-Buo-Ren** [comment]
I can confirm that [reverting commit a1bec173eae16032fb02be01c3efb4b824e2ecd2](https://github.com/Lin-Buo-Ren/snapcraft-desktop-helpers/commits/test-fontconfig) can avoid reproducing this issue.

**Comment by Lin-Buo-Ren** [comment]
Here are the fontconfig rules in my system, just for reference: 

* [_etc_fonts.tar.gz](https://github.com/ubuntu/snapcraft-desktop-helpers/files/2015489/_etc_fonts.tar.gz)
* [_homedir_.config_fontconfig.tar.gz](https://github.com/ubuntu/snapcraft-desktop-helpers/files/2015491/_homedir_.config_fontconfig.tar.gz)

**Comment by Lin-Buo-Ren** [comment]
This issue no longer reproduced now, how weird...
