### ISSUE TITLE
bindtextdomain.so in root of my snap

### ISSUE THREAD

**Issue by popey** [ubuntu/snapcraft-desktop-helpers#125]
I have built a snap which uses desktop-gtk2. Suddenly there's a random library bindtextdomain.so in the root of my project. Googling turns up this project, so I blame you guys :) 
Any chance this can move to $SNAP/lib please? It's a bit messy to just dump it in the root of the snap.

**Comment by oSoMoN** [comment]
Not tested, but PR #127 should do the trick.

**Comment by diddledan** [comment]
@popey you can close this issue now. It's fixed per @oSoMoN 's comment above.
