### ISSUE TITLE
Question: how to inform snapcrafters about the need of rebuilding the snaps?

### ISSUE THREAD

**Issue by meddario** [ubuntu/snapcraft-desktop-helpers#132]
Hi, this is more of a question than an issue. 

Regarding issue #92, there are a lot of people still complaining about the same problem (for example here https://bugs.launchpad.net/ubuntu/+source/snapcraft/+bug/1746710, the number of affected people grows day by day), meaning that many snaps are not being rebuilt using the latest version of this tool.

My question is: is there something that can be done to inform all the snap authors (the people who create the snap packages found in the store) about this? For example sending an email to all the snap authors.

I know that this probably isn't the right place to ask, but I think that this is a serious problem (fortunately with an easy solution) that should be fixed as soon as possible.

**Comment by kenvandine** [comment]
Are the snaps in question under the snapcrafters project?  If so I bet we could trigger builds for them all.  I know all the GNOME snaps have been rebuilt with the fix.

**Comment by meddario** [comment]
I don't really know any snap affected by this problem (the ones i use are gimp, libreoffice and vlc on Ubuntu 16.04). My question originated from the fact that the growth of the number of affected user didn't seem to cease even in the last days, so I was just wondering if there is a way to automatically inform all snap maintainers about the need of the rebuild.
