### ISSUE TITLE
New logo/icon proposal

### ISSUE THREAD

**Issue by mansya** [ubuntu/snapcraft-desktop-helpers#151]
Good day sir. I am a graphic designer and i am interested in designing a logo for your good project. I will be doing it as a gift for free. I just need your permission first before I begin my design. Hoping for your positive feedback. Thanks

**Comment by mansya** [comment]
hi sir. how about this offer? are you interested ?

**Comment by popey** [comment]
@mansya thanks for the offer, but this project doesn't actually need a logo. It's just a set of scripts which are used internally in some other projects.
