### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by larryprice** [ubuntu/snapcraft-desktop-helpers#16]
Should this have a LICENSE file? snappy-playpen is MIT, but most Canonical stuff is GPLv3. I poked through a few of the other parts from [this list](https://wiki.ubuntu.com/snapcraft/parts) and quite a few of them seem to be lacking any information on licensing.

**Comment by didrocks** [comment]
Yeah, I think we should and was planning to before being assigned to other work (but wanted to discuss once people start using them). I would personally go for MIT because people are going to include this in various projects with diverse licenses. Sounds good to you?

**Comment by larryprice** [comment]
Agreed - MIT is probably the best option.
