### ISSUE TITLE
Should LOCPATH not reference `$SNAP/usr/share/locale`?

### ISSUE THREAD

**Issue by diddledan** [ubuntu/snapcraft-desktop-helpers#165]
Ref. the documentation for GNU Libc at https://www.gnu.org/software/libc/manual/html_node/Locale-Names.html

`LOCPATH` environment variable is set to point at `$RUNTIME/usr/lib/locale`. The documentation says that the default path is expected to be `/usr/share/locale` which in the snap world would be `$SNAP/usr/share/locale`.

Should we add or replace the path `$SNAP/usr/share/locale` into the `LOCPATH`?

**Comment by Lin-Buo-Ren** [comment]
`$RUNTIME` is set to `$SNAP` when it is empty at:
https://github.com/ubuntu/snapcraft-desktop-helpers/blob/de8dc06/common/desktop-exports#L58-L59

Not sure when `$RUNTIME` is set though(the platform snaps?), I would suggest inserting `$SNAP/usr/share/locale`after `$RUNTIME/usr/lib/locale` when `$RUNTIME` is set.

**Comment by Lin-Buo-Ren** [comment]
`$RUNTIME` is set at https://github.com/ubuntu/snapcraft-desktop-helpers/blob/479fa0d2478de7dc39edfca3f114f4d91db15b66/gtk/runtime-exports, when the gnome-platform content snap is connected

**Comment by diddledan** [comment]
You're right. I'm wrong :-) Closing.
