### ISSUE TITLE
App with OpenGL not working with host on Wayland

### ISSUE THREAD

**Issue by tpeeters** [ubuntu/snapcraft-desktop-helpers#172]
I created an App (a Python 3 + Qt5 QML app using PySide2) that runs fine on Ubuntu 18.04 with Wayland, but when creating a snap package, the applications does not run on 18.04 with Wayland. On Ubuntu 16.04, or Ubuntu 18.04 using X11 (no Wayland), the snap runs fine too.

When running the snap on Ubuntu 18.04 with Wayland, it shows the following:
https://pastebin.ubuntu.com/p/whWXk2drjW/

The snapcraft.yaml file looks like this: https://pastebin.ubuntu.com/p/kkM2gv2fN5/

Adding:
    environment:
      DISABLE_WAYLAND: 1
in the snapcraft.yaml file under qmenta-app fixes the problem, and the snapped app will run on 18.04 with Wayland too. However, I consider this a workaround because it avoids running the app on Wayland.

**Comment by kenvandine** [comment]
please try to add wayland and desktop to your list of plugs.

**Comment by tpeeters** [comment]
I am running the snap with --devmode, so I think adding plugs does not make a difference.

**Comment by tpeeters** [comment]
Note: I tried adding QT_QPA_PLATFORM=wayland, but it did not help.

**Comment by cgutman** [comment]
I have a PR up to address this #194 

@kenvandine Mind taking a look?
