### ISSUE TITLE
Slow vlc snap start up due to update-mime-database

### ISSUE THREAD

**Issue by anthonywong** [ubuntu/snapcraft-desktop-helpers#173]
VLC snap (r770) takes more than 10 seconds to launch on two machines, not limited to first run. Here are outputs when running `snap run --trace-exec vlc`:
* https://paste.ubuntu.com/p/7qXH6D8NX3/
* https://paste.ubuntu.com/p/s5fYtPK5pY/

I tried to trace the snap's desktop-launch by adding `-x` argument after `#!/bin/bash` to desktop-launch. This is the output: https://paste.ubuntu.com/p/Mz9WhR5DpW/
Lines 413-418 shows update-mime-database is run, because `$needs_update` is true, which is set on line 17, because I do not have `~/.config/user-dirs.{dirs,locale}.md5sum`.  I have only `~/.config/user-dirs.dirs` but no `~/.config/user-dirs.locale`, as such their corresponding `.md5sum` files are not created by desktop-launch.

I manually fixed this by running `xdg-user-dirs-update --force`, which generates `~/.config/user-dirs.locale`. Running `xdg-user-dirs-update` without `--force` does not do that.

**Comment by galgalesh** [comment]
Hi @anthonywong 

Thanks for this investigation!

It's not clear to me how you end up without a `~/.config/user-dirs.locale` file. This file should always be present. Do you have any idea why this was not the case?

**Comment by anthonywong** [comment]
I am not sure, but I guess it could be because this box was installed from a devel Ubuntu series and that's a bug from that.

**Comment by gazhay** [comment]
I too was missing the file, upon creating it with touch and running vlc once, subsequent launches are instant.

**Comment by galgalesh** [comment]
@gazhay Interesting! Do you have any idea how you ended up not having this file? Is this a fresh install or an upgraded machine?

**Comment by gazhay** [comment]
I'm on 18.04 LTS, would have upgraded from 16.04 LTS.

**Comment by galgalesh** [comment]
Ok, I'm guessing this issue is prevalent enough to warrant checking for it in the desktop-launch script and creating the file if it doesn't exist.

**Comment by galgalesh** [comment]
So, I did some more digging into why `~/.config/user-dirs.locale` would not exist. This file is removed when you get the `xdg-user-dirs-gtk` prompt (which asks you if you want to translate the name of your documents etc. directories after you change your language) and you select the "Don't ask me this again" checkbox. The tool then removes the file and will never show again. Thus **not having `~/.config/user-dirs.locale` is a valid state to be in, and desktop-helpers should handle this properly**
