### ISSUE TITLE
Readme is too scant

### ISSUE THREAD

**Issue by popey** [ubuntu/snapcraft-desktop-helpers#183]
Now `snapcraft define (remotepart)` no longer works with bases, it's unfortunately difficult to get to the documentation for each of the parts.

The README.md should really contain the absolute basics as per the output that was in `snapcraft define` to allow visitors to the project to understand how it's used.

**Comment by Lin-Buo-Ren** [comment]
Maybe we should write it in a forum wiki topic and point there instead?

**Comment by popey** [comment]
Yup! That would be good too.
