### ISSUE TITLE
[Qt] Support QTWEBENGINEPROCESS_PATH

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [ubuntu/snapcraft-desktop-helpers#186]
We should consider adding this in our Qt launcher.

Reference: https://doc.qt.io/qt-5/qtwebengine-deploying.html#deploying-qt-webengine-processes

**Comment by pachulo** [comment]
I think that this error I encountered snapping Musescore 3.0 might be related:

- https://musescore.org/en/comment/884393#comment-884393
