### ISSUE TITLE
snap fails when the home directory path contains a symbolic link

### ISSUE THREAD

**Issue by afluegel9** [Ubuntu/snapcraft-desktop-helpers#225]
I'm using microk8s and when it calls snap to run kubectl i get:
"cannot create user data directory: /home/user0815/snap/microk8s/2695: Not a directory"
In strace we can see the truth:
...
4030046 openat(AT_FDCWD, "/", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 4   
4030046 mkdirat(4, "home", 0755)        = -1 EEXIST (File exists)  
4030046 openat(4, "home", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = 5   
4030046 close(4)                        = 0   
4030046 mkdirat(5, "user0815", 0755)     = -1 EEXIST (File exists)   
4030046 openat(5, "user0815", O_RDONLY|O_NOFOLLOW|O_CLOEXEC|O_DIRECTORY) = -1 ENOTDIR (Not a directory)    
4030046 close(5)                        = 0   
4030046 write(2, "cannot create user data directory: /home/user0815/snap/microk8s/2695", 67)   
...

and snap is actually the culprit (see the PID):
4030046 execve("/snap/snapd/current/usr/bin/snap", ["microk8s", "kubectl", "get", "pods"], 0xc0000f4180 /* 23 vars */ <unfinished ...>

It wants to create my home directory (!?!?!?!?!???!??!!?) and when encountering the symlink user0815 it fails.
Symlinks in the home directory path are quite common. Probably not at "snapcraft". However.
So there are several flaws:
The program should not try to create the home directory
The algorithm to determine, if the directory exists, is inappropriate.
The error message is misleading as the issue does not have to do with the entire path /home/user0815/snap/microk8s/2695

An i don't want a visible directory in my home. Please change it to .snap

**Comment by kenvandine** [comment]
I don't think snapcraft-desktop-helpers is involved in this snap.  You should probably file this against snaps at https://bugs.launchpad.net/snapd
