### ISSUE TITLE
Elementary OS support

### ISSUE THREAD

**Issue by develar** [ubuntu/snapcraft-desktop-helpers#32]
It seems that install snap is not integrated into system. AppImage correctly integrated (using https://github.com/electron-userland/electron-builder/blob/master/templates/linux/AppRun.sh).

Is Elementary OS support planned? Is it known issue?

**Comment by didrocks** [comment]
I don't think this issue is linked to the desktop helper itself, which is a developer tool to start (not package) a desktop application on a snap system.

Support for snap in Elementary OS should be opened against the elementary project (I guess, on launchpad). Closing this bug thus.

**Comment by develar** [comment]
@didrocks Please note  — AppImage is correctly integrated because we just use `desktop-file-install`

So, I ask you as electron-builder developer — what's wrong in Snaps that it is not correctly integrated?  I just use `desktop helper` because it is official way (or I am wrong?) to create desktop apps using Snaps.

Off course, I can just not use "desktop helpe" and AppImage approach, but I want to use recommended way. And do not reinvent the wheel.

**Comment by didrocks** [comment]
Contrary to AppImage, the application (and libraries used) by snap applications needs to be relocatable. This isn't always the case, and you need to export some environment variables for your application to know where to look at its resources (like libraries, assets, fonts, themes…).

Also, snaps are contained, unlinke AppImage, so you can't use the global mime cache or gsettings schemas on purpose in snaps. The helpers is there as well to help and avoid people reinventing the wheel in how those should be handled in snaps.

This is basically the 2 ways desktop helpers help developers in packaging snaps, so you are right this is the official ways for now. It would thus be great to have electron-builder supporting snaps and use this launcher.

I do not see the link with elementary OS then? I know upstream is looking at snaps, and are interested into using it, however, if they have some special hooks needed in the desktop helper to support them, we are opened to merge those changes if clearly identified.

Does this make sense?

**Comment by develar** [comment]
@didrocks Thanks for comprehensive answer. So, in short, you have to use some special API to integrate app and it is not supported by elementary OS. I will open issue in the elementary project.
