### ISSUE TITLE
Pulseaudio lib path missing

### ISSUE THREAD

**Issue by tpeeters** [ubuntu/snapcraft-desktop-helpers#37]
libpulsecommon-8.0.so cannot be found as a shared library. For example (after installing the ubuntu-app-platform snap):

```
tim@XPS-13-9350:~$ snap install ubuntu-ui-toolkit-examples --edge
ubuntu-ui-toolkit-examples (edge) 1 from 'canonical' installed
tim@XPS-13-9350:~$ ubuntu-ui-toolkit-examples.jokes 
QGtkStyle could not resolve GTK. Make sure you have installed the proper libraries.
file:///snap/ubuntu-ui-toolkit-examples/7/usr/lib/x86_64-linux-gnu/qt5/examples/ubuntu-ui-toolkit/examples/jokes/jokes.qml:20 plugin cannot be loaded for module "QtMultimedia": Cannot load library /snap/ubuntu-ui-toolkit-examples/7/ubuntu-app-platform/usr/lib/x86_64-linux-gnu/qt5/qml/QtMultimedia/libdeclarative_multimedia.so: (libpulsecommon-8.0.so: cannot open shared object file: No such file or directory)
```

libpulsecommon-8.0.so is available in /snap/current/usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so so I think only the export is missing in snapcraft-desktop-helpers/qt/launcher-specific

**Comment by tpeeters** [comment]
See also PR #25

**Comment by didrocks** [comment]
Ok, a real use case when adding the path is relevant (I don't know why it's working in some other cases though). Let's get that fixed then!
