### ISSUE TITLE
desktop-launch should set GST_PLUGIN_PATH

### ISSUE THREAD

**Issue by michihenning** [ubuntu/snapcraft-desktop-helpers#49]
For the thumbnailer, we need to snap an additional gstreamer plugin (libav). The plugin goes into the usual location (usr/lib/<arch>/gstreamer-1.0) in our snap. However, the plugin isn't found unless we also set GST_PLUGIN_PATH in our code. It would be preferable for desktop-launch to set GST_PLUGIN_PATH to include our snap's usr/lib/<arch>/gstreamer-1.0 directory, so we wouldn't need to do the env var hackery ourselves once our process starts.

Note: I know that GST_PLUGIN_SYSTEM_PATH is set already, but that doesn't help us. We need GST_PLUGIN_PATH to be set as well.

**Comment by didrocks** [comment]
Hey Michi!

I'm unsure to really understand to what path you want to set `GST_PLUGIN_PATH` to. Is that the same path than `GST_PLUGIN_SYSTEM_PATH` (ending up with gstreamer-1.0?). Did you check the gst documentation to see why the system one isn't enough and doesn't load your plugin?

**Comment by michihenning** [comment]
We need the code below in order for gstreamer to find the extra plugin. Without this, it simply doesn't work.

`    char const* snap = getenv("SNAP");
    if (snap)
    {
        char const* arch = getenv("SNAP_LAUNCHER_ARCH_TRIPLET");
        if (!arch || !*arch)
        {
            throw runtime_error("Env var SNAP_LAUNCHER_ARCH_TRIPLET not set");
        }

        string plugin_path = string(snap) + "/usr/lib/" + arch + "/gstreamer-1.0";
        char const* old_plugin_path = getenv("GST_PLUGIN_PATH");
        if (old_plugin_path && *old_plugin_path)
        {
            plugin_path += string(":") + old_plugin_path;
        }
        setenv("GST_PLUGIN_PATH", plugin_path.c_str(), 1);
    }
`

**Comment by didrocks** [comment]
This is the code you are using inside your application, correct?

I would thus just replace in your app/service GST_PLUGIN_PATH to GST_PLUGIN_SYSTEM_PATH then (or better, handle both) if that doesn't influence the gstreamer lib itself.

**Comment by michihenning** [comment]
Yes, that's the application code. The point here is that I don't want to have to set any variable, if I can help it. If desktop-launch sets the variable for us, we don't have to do anything. Whether it's GST_PLUGIN_PATH or GST_PLUGIN_SYSTEM_PATH is really neither here nor there. Gstreamer first looks in the former and then in the latter; if you want to set GST_PLUGIN_SYSTEM_PATH, the application one should come first though.

**Comment by didrocks** [comment]
I guess you need to understand why GST_PLUGIN_SYSTEM_PATH isn't picked up by gstreamer lib itself you need to do that in your application code.

I'm vary on adding another variable while we don't understand the root cause for the lib to not address what's needed based on env variable. If we see, looking at libgstreamer code that it's valid for you to:
1. set this env variable instead of SYSTEM_PATH
2. why the lib don't pick it up itself
I guess that only then we can do such a change.

**Comment by michihenning** [comment]
From memory, when I dump GST_PLUGIN_SYSTEM_PATH, what's in there is the ubuntu-app-platform libdir, but not the libdir of my snap. I'll double-check tomorrow to verify.

**Comment by didrocks** [comment]
That's correct, isn't it included in the ubuntu-app-platform snap? I thought it would? (it's in the gnome one at least).
If you know if it can take a list, I would do $SNAP:$RUNTIME, but I think you should get it included in the ubuntu-app-platform snap.

**Comment by michihenning** [comment]
So, when I dump GST_PLUGIN_SYSTEM_PATH, it is set to /snap/thumbnailer/x1/ubuntu-app-platform/usr/lib/x86_64-linux-gnu/gstreamer-1.0

That's all fine and good; it takes care of locating the gstreamer components that are part of ubuntu-app-platform. But the additional gstreamer plugin we use ends up in /snap/thumbnailer/current/usr/lib/x86_64-linux-gnu/gstreamer-1.0, and that directory is not set by desktop-launch.

What I'm asking for is to set GST_PLUGIN_PATH to $SNAP/usr/lib/$SNAP_LAUNCHER_ARCH_TRIPLET/gstreamer-1.0 as well. That way, we wouldn't have to muck around with setting the variable ourselves. And setting this variable will not do any harm. If a snap doesn't use additional gstreamer plugins, setting the variable has no effect.

**Comment by didrocks** [comment]
Correct, what I'm trying to get it is what plugin exactly is in that path. Is that something which is only for your snap, and dont' need to be shared, or should be in ubuntu-app-platform as more than one snap will use it?

**Comment by michihenning** [comment]
It's libav, which contains a whole bunch of codecs. But I wouldn't put it into the platform snap because it also does H.264, and that has licensing implications. For now, I'd much prefer to keep the plugin private to our snap.

**Comment by didrocks** [comment]
Good enough for me. Doing the change thus :)

**Comment by michihenning** [comment]
Thank you, much appreciate it! :)

**Comment by didrocks** [comment]
yw! and done :)
