### ISSUE TITLE
error while loading shared libraries: libmirclient.so.9: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by kyrofa** [ubuntu/snapcraft-desktop-helpers#63]
My darktable snap works fairly well, and uses the gtk3 helper. It also happens to include the mir client libraries. A few releases of darktable has passed since I built it, however, so I'm trying to bring it up to date. When I try to run my new build, I get:

/snap/darktable-kyrofa/x1/usr/lib/x86_64-linux-gnu/libgtk-3-0/gtk-query-immodules-3.0: error while loading shared libraries: libmirclient.so.9: cannot open shared object file: No such file or directory
darktable: error while loading shared libraries: libmirclient.so.9: cannot open shared object file: No such file or directory

And indeed, the mir client libs don't make it into the final snap. I see commit 290d6d13eee9c48a873f0345218b91dac352a09e started [filtering them out](https://github.com/ubuntu/snapcraft-desktop-helpers/commit/290d6d13eee9c48a873f0345218b91dac352a09e#diff-184032a532406b07009403e26f4fc62fR88), seemingly because they were provided via content sharing. But I don't want to use content sharing here. Shouldn't that filtering be done by a consumer that knows they're using (and indeed, wants to use) content sharing?

**Comment by kyrofa** [comment]
Ah, I see that the description hasn't been updated in the snapcraft parts wiki. This is new:

```
       - access to Mir:
           plugs:
             mir:
             mir-libs:
               default-provider: mir-libs
               interface: content
               target: mir-libs
               content: mir0
```

Changing how this part is used (especially without updating the description in the wiki) hurts.

**Comment by kyrofa** [comment]
Adding

```yaml
desktop-gtk3:
  prime: ['*']
```

to my parts list works around this issue.

**Comment by didrocks** [comment]
Hey Kyle! Thanks for reporting this bug.

I still disagree about the Mir part which was added as an executive decision at the time. Unfortunately, no-one making those decisions are around nowdays, so I'm unsure what this part will become and I will argue to filter it in the desktop part once I have official time to look at the desktop helper again.

Not sure which wiki you are reffering to, not even sure I saw it once :p I only know the wiki where you add your parts, but it doesn't have any reference.
I thought snapcraft define desktop-gtk3 was using the definition in snapcraft.yaml, but it doesn't seem that it's the case as https://github.com/ubuntu/snapcraft-desktop-helpers/blob/master/snapcraft.yaml#L35 and below aren't in the snapcraft part definition, even if refreshed. Any idea?

**Comment by kyrofa** [comment]
Thanks for the quick response Didier, I hope you're well!

The [snapcraft parts wiki](https://wiki.ubuntu.com/snapcraft/parts) is the thing you edit to add this to the parts available in snapcraft. Indeed, it seems that you must duplicate the description in the wiki-- the entry for this part looks like this (note the lack of Mir mentions):

```
---
origin: https://github.com/ubuntu/snapcraft-desktop-helpers.git
maintainer: Snapcraft community <snapcraft@lists.snapcraft.io>
description: |
  Helpers for gtk2, gtk3, qt4 and qt5 or glib minimal launchers.
  It brings the necessary code and exports for binding and using those
  desktop technologies in a relocatable fashion, enabling binding with
  global desktop theme, icon theme, image caching, fonts, mimetype handlers
  application global menu and gsettings integration.
  It also brings basics ubuntu dependency packages.
  
  Usage :
    1. add "after: [desktop-<technology>]" to your launcher:
       - gtk2, gtk3, qt4 and qt5 corresponds to their respective toolkit
         main dependencies and default choices.
       - glib-only enables to compile mime types and gsettings infos. If you
         added your own graphical drivers, it will link them as well.
    2. prepend your command with "desktop-launch", like:
       commands: "desktop-launch foo" if foo is in $PATH. You can as well
       specify: "desktop-launch $SNAP/foo".
    3. add needed plugs to your application:
       - for graphical application:
         plugs: [x11 (or unity7 for appmenu integration)]. Think about adding
         opengl if you need hw acceleration.
       - if your application needs access to sound:
         plugs: [pulseaudio]
       - accessing to user's home directory:
         plugs: [home]
       - read/write to gsettings:
         plugs: [gsettings, home]
         (note that the home plug is needed to read new value)
parts:
  - desktop-gtk2
  - desktop-gtk3
  - desktop-qt4
  - desktop-qt5
  - desktop-glib-only
  - desktop-gnome-platform
---
```

Thankfully this does have a workaround, but do keep it in mind if you're able to get back to these. Thanks man :smiley: .

**Comment by didrocks** [comment]
FYI, as part of a big cleanup and removal (like our SDK platform snap and other things) I did remove the Mir* related things in both gtk and qt parts as we don't target Mir for apps on the desktop anymore.

In case you need this for other kinds of work like IoT base, we can add another launcher flavor specific to it (and according description), maybe we won't call it desktop-launch though, but this is easy enough to modulate :) Keep me posted!

I updated the wiki description as well. Thanks :)
