### ISSUE TITLE
Chinese fonts not rendering correctly for electron apps

### ISSUE THREAD

**Issue by galgalesh** [Ubuntu/snapcraft-desktop-helpers#84]
Chinese fonts don't render correctly for electron apps.

# How to reproduce

Paste the following text as "server name" in the "add server" dialog

```
網站有中、英文版本，也有繁、簡體版，可通過每頁左上角的連結隨時調整。
```

You get white squares.

![image](https://user-images.githubusercontent.com/1492981/32677551-2f998fde-c65f-11e7-82a9-851f4579f564.png)

Downstream issue: https://github.com/snapcrafters/mattermost-desktop/issues/5

**Comment by jhenstridge** [comment]
The best solution here would be to alter the snap to plug the `desktop` interface: that will make the host system fonts visible to the confined application.

Without that, the only fonts visible will be the ones shipped in the snap itself.  The `desktop-gtk2` part could force more fonts to be automatically bundled into the snap, but it is effectively a game of whack a mole: Chinese is missing today, some other language is missing tomorrow.

We can be fairly certain that the user already has fonts covering their native language installed on the host system, so accessing those via the `desktop` interface avoids this entirely.

**Comment by galgalesh** [comment]
Thanks!

At first, adding the `desktop` interface caused all fonts to fail. This was however an issue with the mattermost binary having the `stackexec` bit enabled, causing apparmor to deny access to all files outside of the snap's confinement. After I fixed it, all fonts work now.

For reference for other people having the same issue: https://forum.snapcraft.io/t/fonts-fail-to-load-when-desktop-plug-added/3414/3?u=galgalesh


It might be best to document this though: "use the `desktop` plug to access system fonts".
