### ISSUE TITLE
Add support for Unity8

### ISSUE THREAD

**Issue by fkaleo** [ubuntu/snapcraft-desktop-helpers#9]
In order for an app to communicate with MIR under unity8, the following has to be done:
if [ "$DESKTOP_SESSION" = "unity8" ]; then
    # Qt Platform to Mir
    export QT_QPA_PLATFORM=ubuntumirclient
    # Mir runtime
    export MIR_SOCKET=$XDG_RUNTIME_DIR/mir_socket
    export MIR_CLIENT_PLATFORM_PATH=$SNAP/usr/lib/$ARCH/mir/client-platform
fi

A bunch of apps do it manually already. Can we add it to the desktop-launcher?

**Comment by didrocks** [comment]
sure! That sounds good! :) Mind opening a PR on the Qt5 flavor adding this?
