### ISSUE TITLE
Snap does not respect directory settings

### ISSUE THREAD

**Issue by michalmaria** [ubuntu/snapcraft-desktop-helpers#92]
I'm using Ubuntu 17.10, with system locale set to slovak. Hence my home directory was created with directories using slovak names (Dokumenty, Hudba,...). With some applications (e.g. Spotify, Brave), running `sudo snap install whatever` will result (besides the expected install) in new directories created within my /home (in english).

This was reported [here](https://forum.snapcraft.io/t/snap-does-not-respect-directory-settings/3274).

The same issue apparently happens if the home directory structure is modified with `user-dirs.dirs` (as reported in the link above).

**Comment by kenguru33** [comment]
I can confirm that this also happens on Debian stretch and Fedora 27

**Comment by meddario** [comment]
I can confirm the same in Ubuntu 18.04 with the latest updates.

For example:

`sudo snap install gimp`

start Gimp and check $HOME, the english-named directories are there.

**Comment by gnumdk** [comment]
It's a really important bug? Is Canonical really going to release an LTS distrubiton with such bug. It add unwanted folders in your homedir as soon you run a new snap...

**Comment by kenvandine** [comment]
The fix for this is being reviewed in PR #103

**Comment by meddario** [comment]
Just a question: will this be released for 18.04? It's quite big for an LTS release, the user experience is really poor if you have any non-english locale.

**Comment by kenvandine** [comment]
This is a remote part used at build time. The fix is released, and we've rebuilt all the snaps we maintain to take advantage of the fix.  If there is a specific snap you'd like to see the fix in, I'd suggest filing a bug requesting a rebuild of the snap.

**Comment by meddario** [comment]
All clear! Thanks!
